# <type>: Returns the literal type of the entity (ie: SHEEP)
# <type_name_cased>: Returns the literal type of the entity but not screaming (ie: Sheep)
# <display_name>: Returns the display name or the type_name_cased if it is not named (ie: _jeb)
bucket-style:
  title: "<aqua><display_name> in a Bucket"
  enchantment-glint: true
  use-resource-pack: true
  default-item-model: "minecraft:bucket"

# Whether the plugin should set the textures to the ones specified in texture.yml, defaults are from
# https://modrinth.com/resourcepack/bucket-mobs-resources/versions
# The settings for the bucket-able mobs, or non-bucketable mobs. Fields left empty or non-existent will fall back to default
# And if there is not a default, will default to 'false'
# List of Entity Types here: https://purpurmc.org/javadoc/org/bukkit/entity/EntityType.html
bucket-type-settings:
  default:
    allow: false
    sneak-required: false
    pickup-when-aggro: false
    requires-permission: false
  types:
    VILLAGER:
      allow: true
      sneak-required: true
      requires-permission: true
    SLIME:
      allow: true
      pickup-when-aggro: true
    SHEEP:
      allow: true
    COW:
      allow: true
      sneak-required: true
    PIG:
      allow: true
    MOOSHROOM:
      allow: true
      sneak-required: true
