name: SimpleBucketMobs
group: ADHDMC
version: "${version}"
main: adhdmc.simplebucketmobs.SimpleBucketMobs
api-version: 1.19
authors: [ Rhythmic, Peashooter101 ]
description: Shove your mobs into buckets like Axolotls! :D
commands:
  simplebucketmobs:
    description: "SimpleBucketMobs Base Command."
    aliases: ["sbm", "simplebucketmob"]
permissions:
  simplebucketmobs.bucket.<mob>:
    description: "Allows the user to bucket the specified mob."
    default: false
  simplebucketmobs.bucket.all:
    description: "Allows the user to bucket all enabled mobs."
    default: op
  simplebucketmobs.reload:
    description: "Reload plugin configuration files."
    default: op
  simplebucketmobs.debucket:
    description: "Dump saved mob NBT data from Mob Bucket to chat."